# Generated by Django 4.2.7 on 2024-08-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_clone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
